### PR TITLE
fix: set prop with `background-image` and custom pattern

### PR DESCRIPTION
**Pull request by taoliujun**
when cloneAfter with `backgound`, it will override other background style like `repeat`.
And sometimes, pattern is different with `format=webp`

### CODE REVIEW

**Comment by ai** [comment]
Looks good 👍. Can you add tests and docs?

**Comment by taoliujun** [comment]
> Looks good 👍. Can you add tests and docs?

done.

**Comment by ai** [comment]
Note, that I renamed `pattern` to `check` and use `decl` instead of `decl.value` for better flexibility 7db2e16

**Comment by ai** [comment]
Released in 0.7

**Pull request merged**
